name: 'dbt_stridez'
version: '1.0'
config-version: 2

profile: 'dbt_stridez'

model-paths: ["models"]

models:
  dbt_stridez:
    staging:
      +schema: staging
      +materialized: view

    marts:
      +schema: mart
      +materialized: table
