version: 2

sources:
  - name: raw
    database: demo_vincent_stridez
    schema: raw
    tables:
      - name: ad_campaigns
        description: "Raw ad campaign data from various ad platforms."
        columns:
          - name: campaign_id
            description: "Unique identifier for the ad campaign."
            tests: [not_null, unique]

      - name: orders
        description: "Raw ecommerce orders tied to ad campaigns."
        columns:
          - name: order_id
            description: "Unique order identifier."
            tests: [not_null, unique]
          - name: campaign_id
            description: "Foreign key to ad_campaigns."
            tests:
              - relationships:
                  to: ref('stg_ad_campaigns')
                  field: campaign_id
